### ISSUE TITLE
latest updates break usage with reverse proxy

### ISSUE THREAD

**Issue by Quexer69** [tutumcloud/tutum-docker-clusterproxy#47] opened 2015-04-28 18:23 UTC
Since  I had to redeployed a since 10 days running stack, VIRTUAL_HOST env variable was set to example.com which was possible before. How can I get the haproxy container work again like he previously did.

The application is reachable over the nginx endpoint.

```
[haproxy-1] 2015-04-28T18:11:28.202889535Z   File "/app/haproxy.py", line 310, in main
[haproxy-1] 2015-04-28T18:11:28.202889535Z     update_cfg(cfg, backend_routes, vhost)
[haproxy-1] 2015-04-28T18:11:28.202889535Z   File "/app/haproxy.py", line 169, in update_cfg
[haproxy-1] 2015-04-28T18:11:28.202889535Z     service_name = service_name.upper()
[haproxy-1] 2015-04-28T18:11:28.202889535Z AttributeError: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:11:58.764401740Z ERROR:__main__:Error: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:11:58.764401740Z Traceback (most recent call last):
[haproxy-1] 2015-04-28T18:11:58.764401740Z   File "/app/haproxy.py", line 310, in main
[haproxy-1] 2015-04-28T18:11:58.764401740Z     update_cfg(cfg, backend_routes, vhost)
[haproxy-1] 2015-04-28T18:11:58.764401740Z   File "/app/haproxy.py", line 169, in update_cfg
[haproxy-1] 2015-04-28T18:11:58.764401740Z     service_name = service_name.upper()
[haproxy-1] 2015-04-28T18:11:58.764401740Z AttributeError: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:12:29.350944140Z ERROR:__main__:Error: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:12:29.350944140Z Traceback (most recent call last):
[haproxy-1] 2015-04-28T18:12:29.350944140Z   File "/app/haproxy.py", line 310, in main
[haproxy-1] 2015-04-28T18:12:29.350944140Z     update_cfg(cfg, backend_routes, vhost)
[haproxy-1] 2015-04-28T18:12:29.350944140Z   File "/app/haproxy.py", line 169, in update_cfg
[haproxy-1] 2015-04-28T18:12:29.350944140Z     service_name = service_name.upper()
[haproxy-1] 2015-04-28T18:12:29.350944140Z AttributeError: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:12:59.939803434Z ERROR:__main__:Error: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:12:59.939803434Z Traceback (most recent call last):
[haproxy-1] 2015-04-28T18:12:59.939803434Z   File "/app/haproxy.py", line 310, in main
[haproxy-1] 2015-04-28T18:12:59.939803434Z     update_cfg(cfg, backend_routes, vhost)
[haproxy-1] 2015-04-28T18:12:59.939803434Z   File "/app/haproxy.py", line 169, in update_cfg
[haproxy-1] 2015-04-28T18:12:59.939803434Z     service_name = service_name.upper()
[haproxy-1] 2015-04-28T18:12:59.939803434Z AttributeError: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:13:16.524865Z (Logs not available)
[haproxy-1] 2015-04-28T18:13:30.566383159Z ERROR:__main__:Error: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:13:30.566383159Z Traceback (most recent call last):
[haproxy-1] 2015-04-28T18:13:30.566383159Z   File "/app/haproxy.py", line 310, in main
[haproxy-1] 2015-04-28T18:13:30.566383159Z     update_cfg(cfg, backend_routes, vhost)
[haproxy-1] 2015-04-28T18:13:30.566383159Z   File "/app/haproxy.py", line 169, in update_cfg
[haproxy-1] 2015-04-28T18:13:30.566383159Z     service_name = service_name.upper()
[haproxy-1] 2015-04-28T18:13:30.566383159Z AttributeError: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:14:01.072999915Z ERROR:__main__:Error: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:14:01.072999915Z Traceback (most recent call last):
[haproxy-1] 2015-04-28T18:14:01.072999915Z   File "/app/haproxy.py", line 310, in main
[haproxy-1] 2015-04-28T18:14:01.072999915Z     update_cfg(cfg, backend_routes, vhost)
[haproxy-1] 2015-04-28T18:14:01.072999915Z   File "/app/haproxy.py", line 169, in update_cfg
[haproxy-1] 2015-04-28T18:14:01.072999915Z     service_name = service_name.upper()
[haproxy-1] 2015-04-28T18:14:01.072999915Z AttributeError: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:14:31.632991983Z ERROR:__main__:Error: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:14:31.632991983Z Traceback (most recent call last):
[haproxy-1] 2015-04-28T18:14:31.632991983Z   File "/app/haproxy.py", line 310, in main
[haproxy-1] 2015-04-28T18:14:31.632991983Z     update_cfg(cfg, backend_routes, vhost)
[haproxy-1] 2015-04-28T18:14:31.632991983Z   File "/app/haproxy.py", line 169, in update_cfg
[haproxy-1] 2015-04-28T18:14:31.632991983Z     service_name = service_name.upper()
[haproxy-1] 2015-04-28T18:14:31.632991983Z AttributeError: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:15:02.132148418Z ERROR:__main__:Error: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:15:02.132148418Z Traceback (most recent call last):
[haproxy-1] 2015-04-28T18:15:02.132148418Z   File "/app/haproxy.py", line 310, in main
[haproxy-1] 2015-04-28T18:15:02.132148418Z     update_cfg(cfg, backend_routes, vhost)
[haproxy-1] 2015-04-28T18:15:02.132148418Z   File "/app/haproxy.py", line 169, in update_cfg
[haproxy-1] 2015-04-28T18:15:02.132148418Z     service_name = service_name.upper()
[haproxy-1] 2015-04-28T18:15:02.132148418Z AttributeError: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:15:32.691485131Z ERROR:__main__:Error: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:15:32.691485131Z Traceback (most recent call last):
[haproxy-1] 2015-04-28T18:15:32.691485131Z   File "/app/haproxy.py", line 310, in main
[haproxy-1] 2015-04-28T18:15:32.691485131Z     update_cfg(cfg, backend_routes, vhost)
[haproxy-1] 2015-04-28T18:15:32.691485131Z   File "/app/haproxy.py", line 169, in update_cfg
[haproxy-1] 2015-04-28T18:15:32.691485131Z     service_name = service_name.upper()
[haproxy-1] 2015-04-28T18:15:32.691485131Z AttributeError: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:16:03.254170110Z ERROR:__main__:Error: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:16:03.254170110Z Traceback (most recent call last):
[haproxy-1] 2015-04-28T18:16:03.254170110Z   File "/app/haproxy.py", line 310, in main
[haproxy-1] 2015-04-28T18:16:03.254170110Z     update_cfg(cfg, backend_routes, vhost)
[haproxy-1] 2015-04-28T18:16:03.254170110Z   File "/app/haproxy.py", line 169, in update_cfg
[haproxy-1] 2015-04-28T18:16:03.254170110Z     service_name = service_name.upper()
[haproxy-1] 2015-04-28T18:16:03.254170110Z AttributeError: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:16:33.855134745Z ERROR:__main__:Error: 'NoneType' object has no attribute 'upper'
[haproxy-1] 2015-04-28T18:16:33.855134745Z Traceback (most recent call last):
[haproxy-1] 2015-04-28T18:16:33.855134745Z   File "/app/haproxy.py", line 310, in main
[haproxy-1] 2015-04-28T18:16:33.855134745Z     update_cfg(cfg, backend_routes, vhost)
[haproxy-1] 2015-04-28T18:16:33.855134745Z   File "/app/haproxy.py", line 169, in update_cfg
[haproxy-1] 2015-04-28T18:16:33.855134745Z     service_name = service_name.upper()
[haproxy-1] 2015-04-28T18:16:33.855134745Z AttributeError: 'NoneType' object has no attribute 'upper'
```

**Comment by Quexer69** [comment] 2015-04-28 18:34
edit: we've build from commit 7b07d5743ae55ccc1471bdcf43f99e110542622d which works as expected

**Comment by tifayuki** [comment] 2015-04-28 18:37
How did you run haproxy and link to other containers?

**Comment by Quexer69** [comment] 2015-04-29 08:30
```
appcli:
    command: 'sh /root/tutum.sh'
    image: 'tutum.co/USER/IMAGE:latest'
    links:
        - 'appnginx:WEB'
        - 'mariadb:DB'
    tags:
        - app
    volumes_from:
        - appsrc
appfpm:
    environment:
        SOME_ENV_VARS
    image: 'schmunk42/php:5.6-fpm-yii-2.0.3-runtime'
    links:
        - 'mariadb:DB'
    tags:
        - app
    volumes_from:
        - appsrc
appnginx:
    environment:
        NGINX_ERROR_LOG_LEVEL: notice
        VIRTUAL_HOST: example.com
    image: 'schmunk42/nginx:1.7'
    links:
        - 'appfpm:PHPFPM'
    ports:
        - '80'
    tags:
        - app
    volumes_from:
        - appsrc
appsrc:
    command: 'tail -f /dev/null'
    image: 'tutum.co/USER/IMAGE:latest'
    tags:
        - app
    volumes:
        - /app
haproxy:
    environment:
        BACKEND_PORT: 80
        VIRTUAL_HOST: example.com
    image: tutum/haproxy
    links:
        - 'appnginx:appnginx'
    ports:
        - '80'
    roles:
        - global
    tags:
        - proxy
```

**Comment by tifayuki** [comment] 2015-04-29 09:00
```
haproxy:
    environment:
        BACKEND_PORT: 80
        VIRTUAL_HOST: example.com
```
The `VIRTUAL_HOST` here is wrong. If you want to set `VIRTUAL_HOST` in haproxy, the syntax is `link_alias1=domain1, domain2, link_alias2=domain3`. As a result, in your case, you should use `VIRTUAL_HOST: appnginx=example.com` instead of `VIRTUAL_HOST: example.com`

Moreover, since you have specified `VIRTUAL_HOST` in `appnginx`, there is no need to set it again in haproxy. Simply remove `VIRTUAL_HOST: example.com` in haproxy will work.

Let me know if it works for you.

PS: If you set `VIRTUAL_HOST` in haproxy, what you set in the linked containers will be ignored.
PPS: I will fix the issue of throwing out the exception

**Comment by schmunk42** [comment] 2015-04-29 14:05
@tifayuki We're using the haproxy together with this [nginx reverse proxy](https://github.com/jwilder/nginx-proxy). The problem is, that the reverse proxy also uses `VIRTUAL_HOST` but with another syntax (domain only or regexp).

At least until 7b07d57 the haproxy did not care about the "wrong" `VIRTUAL_HOST` setting. The variable was just used by the reverse proxy to determine the hostname.

Could you create a tag for the commit above eg. 0.1.0, so we can stay on that version?

Options to solve this are either for us to build custom images without conflicting ENV variables or even better to make the desired behavior configurable.

**Comment by tifayuki** [comment] 2015-04-29 16:00
@schmunk42 
I pushed a fix to ignore the invalid `VIRTUAL_HOST` host on haproxy container.
Let me know if the it fixes the issue.

**Comment by schmunk42** [comment] 2015-05-06 22:01
Yes, this is fixed. Thanks.

Although we're still trying out older versions of haproxy, since we have unclear networking issues since 1-2 weeks. Will let you know when I find a correlation to haproxy.

**Closed** 2015-05-13 13:59 UTC
